package io.github.vivitoto.vanga.ui.strings

val EnStrings = AppStrings(
    filters = FilterStrings(
        anyValue = "任意",

        filterTagsSearch = "搜索标签",
        filterTagsReset = "重置",
        filterTagsGenreLabel = "流派",
        filterTagsTagsLabel = "标签",
        filterTagsShowMore = "显示更多",
        filterTagsShowLess = "收起",
        includeIfAllMatch = "全部匹配",
        includeIfAnyMatch = "任意匹配",
        excludeIfAllMatch = "全部匹配",
        excludeIfAnyMatch = "任意匹配",
    ),
    seriesFilter = SeriesFilterStrings(
        resetFilters = "重置筛选",
        hideFilters = "隐藏筛选",
        anyValue = "任意",
        search = "搜索",

        sort = "排序",
        sortTitleAsc = "标题升序",
        sortTitleDesc = "标题降序",
        sortDateAddedAsc = "最早添加",
        sortDateAddedDesc = "最近添加",
        sortReleaseDateAsc = "最早发布日期",
        sortReleaseDateDesc = "最新发布日期",
        sortUpdatedAsc = "最早更新",
        sortUpdatedDesc = "最近更新",
        sortFolderNameAsc = "文件夹名升序",
        sortFolderNameDesc = "文件夹名降序",
        sortBooksCountAsc = "书籍最少",
        sortBooksCountDesc = "书籍最多",

        filterTagsLabel = "筛选标签",
        readStatus = "阅读状态",
        readStatusUnread = "未读",
        readStatusInProgress = "阅读中",
        readStatusRead = "已读",

        publicationStatus = "出版状态",
        pubStatusEnded = "已完结",
        pubStatusOngoing = "连载中",
        pubStatusAbandoned = "已放弃",
        pubStatusHiatus = "暂停",

        complete = "已完结",
        oneshot = "单本",
        authors = "作者",
        publisher = "出版社",
        language = "语言",
        releaseDate = "发布日期",
        ageRating = "年龄分级"
    ),
    booksFilter = BookFilterStrings(
        sort = "排序",
        sortNumberAsc = "升序",
        sortNumberDesc = "降序",

        sortFileNameAsc = "文件名升序",
        sortFileNameDesc = "文件名降序",
        sortReleaseDateAsc = "最新发布日期",
        sortReleaseDateDesc = "最早发布日期",

        readStatus = "阅读状态",
        readStatusUnread = "未读",
        readStatusInProgress = "阅读中",
        readStatusRead = "已读",

        authors = "作者",
        tags = "筛选标签",
    ),
    seriesView = SeriesViewStrings(
        statusEnded = "已完结",
        statusOngoing = "连载中",
        statusAbandoned = "已放弃",
        statusHiatus = "暂停",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
        readingDirectionVertical = "竖排",
        readingDirectionWebtoon = "条漫",
    ),
    seriesEdit = SeriesEditStrings(
        title = "标题",
        sortTitle = "排序标题",
        summary = "简介",
        language = "语言",

        status = "状态",
        statusEnded = "已完结",
        statusOngoing = "连载中",
        statusAbandoned = "已放弃",
        statusHiatus = "暂停",

        readingDirection = "阅读方向",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
        readingDirectionVertical = "竖排",
        readingDirectionWebtoon = "条漫",
        publisher = "出版社",
        ageRating = "年龄分级",
        totalBookCount = "总书籍数"
    ),
    bookEdit = BookEditStrings(
        title = "标题",
        number = "编号",
        sortNumber = "排序编号",
        summary = "简介",
        releaseDate = "发布日期",
        isbn = "ISBN"
    ),
    libraryEdit = LibraryEditStrings(
        emptyTrashAfterScan = "每次扫描后自动清空回收站",
        scanForceModifiedTime = "强制使用目录修改时间",
        scanOnStartup = "启动时扫描",
        oneshotsDirectory = "单本目录",
        excludeDirectories = "排除目录",

        scanInterval = "扫描间隔",
        scanIntervalDisabled = "禁用",
        scanIntervalHourly = "每小时",
        scanIntervalEvery6H = "每 6 小时",
        scanIntervalEvery12H = "每 12 小时",
        scanIntervalDaily = "每天",
        scanIntervalWeekly = "每周",

        hashFiles = "计算文件哈希",
        hashPages = "计算页面哈希",
        analyzeDimensions = "分析页面尺寸",
        repairExtensions = "自动修复错误文件扩展名",
        convertToCbz = "自动转换为 CBZ",
        seriesCover = "系列封面",
        coverFirst = "第一本",
        coverFirstUnreadOrFirst = "优先第一本未读，否则第一本",
        coverFirstUnreadOrLast = "优先第一本未读，否则最后一本",
        coverLast = "最后一本"
    ),
    userEdit = UserEditStrings(
        contentRestrictions = "内容限制",
        age = "年龄",
        labelsAllow = "只允许标签",
        labelsExclude = "排除标签",
        ageRestriction = "年龄限制",
        ageRestrictionNone = "不限制",
        ageRestrictionAllowOnly = "只允许低于",
        ageRestrictionExclude = "排除高于"
    ),
    reader = ReaderStrings(
        zoom = "缩放",
        readerType = "阅读器类型",
        readerPaged = "分页",
        readerContinuous = "连续",
        stretchToFit = "拉伸小图",
        decoder = "图片解码/采样器",
        pagesInfo = "页面信息",
        pageNumber = "页",
        memoryUsage = "内存占用",
        pageDisplaySize = "显示尺寸",
        pageOriginalSize = "原始尺寸",
    ),
    pagedReader = PagedReaderStrings(
        scaleType = "缩放方式",
        scaleScreen = "适应屏幕",
        scaleFitWidth = "适应宽度",
        scaleFitHeight = "适应高度",
        scaleOriginal = "原始大小",
        readingDirection = "阅读方向",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
        layout = "页面布局",
        layoutSinglePage = "单页",
        layoutDoublePages = "双页",
        layoutDoublePagesNoCover = "双页（无封面）",
        offsetPages = "双页偏移",
    ),
    continuousReader = ContinuousReaderStrings(
        sidePadding = "侧边距",
        pageSpacing = "页面间距",
        readingDirection = "阅读方向",
        readingDirectionTopToBottom = "从上到下",
        readingDirectionLeftToRight = "从左到右",
        readingDirectionRightToLeft = "从右到左",
    ),
    settings = SettingsStrings(
        serverSettings = "服务器设置",
        thumbnailSize = "缩略图尺寸",
        thumbnailSizeDefault = "默认（300px）",
        thumbnailSizeMedium = "中等（600px）",
        thumbnailSizeLarge = "大（900px）",
        thumbnailSizeXLarge = "超大（1200px）",

        thumbnailRegenTitle = "重新生成缩略图",
        thumbnailRegenBody = "缩略图尺寸已更改，是否重新生成书籍缩略图？",
        thumbnailRegenIfBigger = "是，仅尺寸变大时",
        thumbnailRegenAllBooks = "是，所有书籍",
        thumbnailRegenNo = "否",

        deleteEmptyCollections = "扫描后删除空合集",
        deleteEmptyReadLists = "扫描后删除空阅读清单",
        taskPoolSize = "任务线程数",
        rememberMeDurationDays = "记住登录时长（天）",
        renewRememberMeKey = "重新生成 RememberMe 密钥",
        serverPort = "服务器端口",
        serverContextPath = "基础 URL",
        requiresRestart = "需要重启后生效",
        serverSettingsDiscard = "放弃",
        serverSettingsSave = "保存更改",

        appTheme = "主题",
        appThemeSystem = "跟随系统",
        appThemeDark = "深色",
        appThemeLight = "浅色",
        imageCardSize = "网格视图封面卡片大小（最小显示尺寸）",
        decoder = "图片解码/采样器",
        epubReaderTypeKomga = "Vanga 兼容 EPUB 阅读器",
        epubReaderTypeTtsu = "完整排版 EPUB 阅读器"
    ),
    errorCodes = ErrorCodes(
        err1000 = "分析时无法访问文件",
        err1001 = "不支持该媒体类型",
        err1002 = "不支持加密 RAR 压缩包",
        err1003 = "不支持固实 RAR 压缩包",
        err1004 = "不支持分卷 RAR 压缩包",
        err1005 = "分析书籍时发生未知错误",
        err1006 = "书籍不包含任何页面",
        err1007 = "部分条目无法分析",
        err1008 = "获取书籍条目时发生未知错误",
        err1009 = "同名阅读清单已存在",
        err1015 = "解析 ComicRack CBL 时出错",
        err1016 = "目录不可访问或不是目录",
        err1017 = "不能扫描已属于现有书库的文件夹",
        err1018 = "文件未找到",
        err1019 = "不能导入已属于现有书库的文件",
        err1020 = "要升级的书籍不属于指定系列",
        err1021 = "目标文件已存在",
        err1022 = "新导入的书籍无法扫描",
        err1023 = "书籍已在阅读清单中",
        err1024 = "OAuth2 登录错误：缺少邮箱属性",
        err1025 = "OAuth2 登录错误：不存在使用该邮箱的本地用户",
        err1026 = "OpenID Connect 登录错误：邮箱未验证",
        err1027 = "OpenID Connect 登录错误：缺少 email_verified 属性",
        err1028 = "OpenID Connect 登录错误：缺少邮箱属性",
        err1029 = "ComicRack CBL 不包含任何 Book 元素",
        err1030 = "ComicRack CBL 没有 Name 元素",
        err1031 = "ComicRack CBL Book 缺少系列或编号",
        err1032 = "EPUB 文件媒体类型错误",
        err1033 = "部分条目缺失",
        err1034 = "已存在使用该备注的 API 密钥",
        err1035 = "获取 EPUB 目录时出错",
        err1036 = "获取 EPUB 地标时出错",
        err1037 = "获取 EPUB 页面列表时出错",
        err1038 = "获取 EPUB divina 页面时出错",
        err1039 = "获取 EPUB 位置时出错",
    ),
    komf = KomfStrings(
        providerSettings = KomfProviderSettingsStrings(
            providerAniList = "AniList",
            providerBangumi = "Bangumi",
            providerBookWalker = "Bookwalker Global",
            providerComicVine = "ComicVine",
            providerHentag = "Hentag",
            providerKodansha = "Kodansha US",
            providerMal = "MyAnimeList",
            providerMangaBaka = "MangaBaka",
            providerMangaUpdates = "MangaUpdates",
            providerMangaDex = "MangaDex",
            providerNautiljon = "Nautiljon",
            providerNHentai = "nHentai",
            providerEHentai = "EHentai / ExHentai",
            providerYenPress = "YenPress",
            providerViz = "Viz",
            providerWebtoons = "Webtoons",
        )
    ),
    imageSettings = ImageSettingsStrings(
        upsamplingMode = "放大采样方式",
        upsamplingModeNearest = "最近邻",
        upsamplingModeBilinear = "双线性",
        upsamplingModeMitchell = "双三次 Mitchell",
        upsamplingModeCatmullRom = "双三次 Catmull-Rom",
        downsamplingKernel = "缩小采样核",
        downsamplingKernelNearest = "最近邻",
        downsamplingKernelLinear = "线性",
        downsamplingKernelCubic = "三次",
        downsamplingKernelMitchell = "Mitchell",
        downsamplingKernelLanczos2 = "Lanczos2",
        downsamplingKernelLanczos3 = "Lanczos3",
        downsamplingKernelMKS2013 = "Magic Kernel Sharp 2013",
        downsamplingKernelMKS2021 = "Magic Kernel Sharp 2021",
        downsamplingKernelDefault = "默认",
    ),
)
